

name: "macOS vagrant kvm qemu libvirt CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  macos-latest-vagrant:
      name: "vagrant macos-latest macos-latest 10.15.7 rust"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 3.2.6   
      - name: "deploy vagrant"
        run:   | 
          # brew cask install virtualbox
          # brew cask install vagrant
          brew install virtualbox
          brew install vagrant  
          mkdir ~/vms
          touch ~/vms/Vagrantfile
          cat<<EOF | sudo tee -a ~/vms/Vagrantfile
          # -*- mode: ruby -*-
          # vi: set ft=ruby :
          VM_BOX  = 'ubuntu/xenial64'
          NETWORK = 'forwarded_port'
          GUEST_PORT = 80
          HOST_PORT = 9000
          Vagrant.configure(2) do |config|
            config.vm.box = VM_BOX
            config.vm.network NETWORK, guest: GUEST_PORT, host: HOST_PORT
            config.vm.provider "virtualbox" do |vb|
              vb.memory = 1024
            end
            config.vm.provision 'shell', inline: <<-SHELL
              echo 'ubuntu:ubuntu' | sudo chpasswd
              hostnamectl status
            SHELL
          end
          EOF
          cat ~/vms/Vagrantfile
          mkdir ~/vms && vagrant up

  macos-latest-vagrant-libvirt-qemu:
      name: "vagrant macos-latest macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 3.2.6   
      - name: "deploy vagrant libvirt qemu"
        run:   | 
          # brew cask install virtualbox
          # brew cask install vagrant
          brew install virtualbox
          brew install vagrant          
          brew install libiconv gcc libvirt
          /opt/vagrant/embedded/bin/ruby --version
          CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/local/include/libvirt with-libvirt-lib=/usr/local/lib' \
          GEM_HOME=~/.vagrant.d/gems/2.4.6 \
          GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems \
          PATH=/opt/vagrant/embedded/bin:$PATH \
          vagrant plugin install vagrant-libvirt
          mkdir ~/vms
          touch ~/vms/Vagrantfile
          cat<<EOF | sudo tee -a ~/vms/Vagrantfile
          Vagrant.configure("2") do |config|
            config.vm.box = "fedora/31-cloud-base"
            config.vm.provider :libvirt do |libvirt|
              libvirt.host = "libvirt-host.example.com"
              libvirt.connect_via_ssh = true
            end
          end
          EOF
          cat ~/vms/Vagrantfile
          mkdir ~/vms && vagrant up  --provider=libvirt   
   
          
  macos-latest-libvirt-qemu:
      name: "libvirt qemu macos-latest macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 3.2.6  
      - name: "deploy qemu libvirt"
        run:   | 
          brew install qemu gcc libvirt
          echo 'security_driver = "none"' >> /usr/local/etc/libvirt/qemu.conf
          echo "dynamic_ownership = 0" >> /usr/local/etc/libvirt/qemu.conf
          echo "remember_owner = 0" >> /usr/local/etc/libvirt/qemu.conf
          brew services start libvirt
          mkdir ~/vms && cd ~/vms
          qemu-img create -f qcow2 ubuntu.qcow2 50g     
      